doc/urls.py
# doc/urls.py
from django.urls import path

from . import views

app_name = 'doc'

urlpatterns = [
    path("", views.docs, name="home"),
    path("add/", views.doc_add, name="add"),
    path("<int:id>/", views.doc, name="detail"),
    path("<int:id>/pdf", views.create_pdf, name="create-pdf"),
    path("<int:id>/edit/", views.doc_edit, name="edit"),
    path("<int:id>/make/version/", views.doc_make_version, name="make-version"),
    path("<int:id>/delete/", views.doc_delete, name="delete"),
    path("<int:id>/restore/", views.doc_restore, name="restore"),
    path("<int:id>/extract/", views.doc_extract, name="extract"),
    path("<int:id>/add_log/", views.doc_add_log, name="add-log"),
    path("<int:id>/flag/", views.doc_toggle_flag, name="toggle-flag"),
    path("<int:id>/react_time/", views.doc_set_reactivation_time, name="set-react-time"),
    path("<int:id>/deadline/", views.doc_set_deadline, name="set-deadline"),
    path("<int:id>/archive/", views.doc_toggle_archive, name="toggle-archive"),
    path("<int:id>/checklist/", views.edit_checklist, name="edit-checklist"),
    path("<int:id>/checkitem/", views.check_checklist, name="check-item"),
    path("<int:id>/complete/", views.doc_toggle_completed, name="toggle-complete"),
    path("tr/analyse/selection/", views.time_analyse_selection, name="tr-analyse-selection"),
    path("tr/analyse/preview", views.time_analyse_preview, name="tr-analyse-preview"),
    path("tr/analyse/download", views.time_analyse_download, name="tr-analyse-download"),
    path("tr/set/settled", views.time_records_set_settled, name="tr-set-settled"),
    path("tr/set/deleted", views.time_records_set_deleted, name="tr-set-deleted"),
    path("database/cleanup", views.cleanup_database, name="cleanup-database"),
    path("filesystem/cleanup", views.cleanup_filesystem, name="cleanup-filesystem"),
    path("database/dump", views.dump_database, name="dump-database"),
    path("status/", views.status, name="status"),
    path("update/bulk", views.bulk_update, name="bulk-update"),
    path("add/short", views.doc_add_short, name="add-short"),
    path("<int:doc_id>/add_time/", views.time_add, name="time-add"),
    path("tags/suggest/", views.suggest_tags, name="tag-suggest"),
]

doc/views.py
import csv
import datetime
import difflib
import io
import os
import re
import shutil
import subprocess
import tempfile
import zipfile
from decimal import Decimal
from io import BytesIO
from itertools import groupby

import openpyxl
from bs4 import BeautifulSoup
from django.conf import settings
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.contenttypes.models import ContentType
from django.db import connection
from django.db.models import Min, Max
from django.db.models import Subquery
from django.db.models.functions import Lower
from django.db.utils import OperationalError
from django.http import HttpResponseRedirect, HttpResponse
from django.template.response import TemplateResponse
from django.urls import reverse
from django.utils import timezone
from django.utils.dateparse import parse_date
from django.utils.dateparse import parse_datetime
from django.utils.timezone import localtime
from openpyxl.styles import Alignment, Border, Side
from taggit.models import Tag, TaggedItem

from .forms import DocForm, TimeRecordForm, CleanupForm
from .markdown import md2html
from .models import Doc, TimeRecord
from .models import File
from .utils import extract_selected_info_from_url
from django.core.files import File as DjangoFile
import traceback
from pathlib import Path
from django.db.models import Count


def get_tags_grouped(tags):
    """
    Von jedem Anfangsbuchstaben werde jeweils nur die 5 häufigsten zur Anzeige gebracht.
    """
    try:
        grouped = []
        tags_sorted = sorted(tags, key=lambda t: (t.slug[0].upper(), -getattr(t, 'num_times', 0)))
        for first_letter, group in groupby(tags_sorted, key=lambda t: t.slug[0].upper()):
            group_list = list(group)
            top_tags = sorted(group_list[:5], key=lambda t: t.slug.lower())  # alphabetisch sortieren nach Begrenzung
            for i, tag in enumerate(top_tags):
                tag.is_last_in_group = (i == len(top_tags) - 1)
            grouped.append((first_letter, top_tags))
        return grouped
    except Exception as e:
        return []


def parse_valid_date(value, fallback):
    try:
        parsed = parse_date(value)
        return parsed or fallback
    except Exception:
        return fallback


def flatten_settings(data, prefix=''):
    flat = {}
    if isinstance(data, dict):
        for key, value in data.items():
            full_key = f"{prefix}.{key}" if prefix else key
            flat.update(flatten_settings(value, full_key))
    else:
        flat[prefix] = data
    return flat


@login_required
@permission_required("doc.search")
def docs(request):
    """List of documents."""

    tags = None
    error = False
    num_matches = 0

    if request.GET:
        params = request.GET.dict()
        request.session['docs_params'] = params
    else:
        params = request.session.get('docs_params', {})

    asc = bool(int(params.get('asc', 0)))
    oby = params.get('orderby', 'created')
    oby2 = oby
    if oby == 'updated':
        oby = 'updated_at'
    elif oby == 'title':
        oby = 'title'
    elif oby == 'time':
        oby = 'time'
    else:
        oby = 'created_at'
    if not asc:
        oby = f'-{oby}'

    search_string = params.get('search', False)
    try:
        if search_string:
            entities = Doc.objects.match(search_string)
        else:
            entities = Doc.objects.all()
        if not params.get('ipr', False):
            # Do not include previous revisions.
            entities = entities.exclude(successor__isnull=False)
        if not params.get('idr', False):
            # Do not include deleted resources.
            entities = entities.exclude(successor__isnull=True, deleted_at__isnull=False)
        if not params.get('iar', False):
            # Do not include archived resources.
            entities = entities.exclude(is_archived=True)
        if params.get('flg', False):
            entities = entities.filter(is_flagged=True)
        if params.get('ustr', False):
            entities = entities.filter(has_unsettled_tr=True)
        if params.get('cgte', False):
            entities = entities.filter(created_at__gte=timezone.make_aware(parse_datetime(params.get('cgte'))))
        if params.get('clte', False):
            entities = entities.filter(created_at__lte=timezone.make_aware(parse_datetime(params.get('clte'))))
        if params.get('ugte', False):
            entities = entities.filter(updated_at__gte=timezone.make_aware(parse_datetime(params.get('ugte'))))
        if params.get('ulte', False):
            entities = entities.filter(updated_at__lte=timezone.make_aware(parse_datetime(params.get('ulte'))))
        if params.get('tgte', False):
            entities = entities.filter(time__gte=timezone.make_aware(parse_datetime(params.get('tgte'))))
        if params.get('tlte', False):
            entities = entities.filter(time__lte=timezone.make_aware(parse_datetime(params.get('tlte'))))
        num_matches = entities.count()
        entities = entities.order_by(oby)[:100]
        entity_ids = [e.id for e in entities]
        available_tags = Doc.tags \
                             .most_common(extra_filters={'doc__in': entity_ids}) \
                             .filter(num_times__lt=len(entity_ids), num_times__gt=0) \
                             .order_by('-num_times', 'name')[:1000]
        if search_string:
            tags = [tag for tag in available_tags if tag.name.lower() not in search_string.lower()]
        else:
            tags = [tag for tag in available_tags]
    except OperationalError as oe:
        entities = Doc.objects.filter(deleted_at__isnull=True, is_archived=False).order_by('-id')[:10]
        error = oe
        print(oe)
    except Exception as e:
        print(e.__traceback__)

    if False:
        print("===================================")
        for query in connection.queries:
            time = float(query['time'])
            print(f"{time}  s: {query['sql']}")
            print("--------------------------------")

    return TemplateResponse(request, "docs.html", {
        'page_title': 'Search Resources',
        'entities': entities,
        'tags': get_tags_grouped(tags),
        'error': error,
        'asc': asc,
        'oby': oby2,
        'params': params,
        'num_matches': num_matches,
    })


@login_required
@permission_required("doc.add_time_record")
def time_add(request, **kwargs):
    """Add a new time record"""

    doc_id = kwargs.get('doc_id')

    if request.method != 'POST':
        return HttpResponseRedirect(reverse("doc__detail", args=(doc_id,)))

    try:
        doc = Doc.objects.get(pk=doc_id)
    except Doc.DoesNotExist as e:
        return TemplateResponse(request, "doc.html", {
            'page_title': f"Documentation - ID {doc_id}",
            'doc_id': doc_id,
            'error': 404,
        })

    trForm = TimeRecordForm(request.POST, user=request.user)
    if trForm.is_valid():
        time_record = trForm.save(commit=False)
        time_record.doc = doc
        time_record.save()
        doc.save()

    return HttpResponseRedirect(reverse("doc__detail", args=(doc_id,)))


@login_required
@permission_required("doc.time_records_set_settled")
def time_records_set_settled(request, **kwargs):
    """
    Sets the selected time records to settled.
    """

    if not request.POST:
        return HttpResponseRedirect(reverse("docs"))

    success = False
    error = False

    try:
        trs = TimeRecord.objects.filter(id__in=request.POST.getlist('tr') or [], user=request.user)
        for tr in trs:
            tr.settled_at = timezone.now()
            tr.save()
            tr.doc.save()
            success = [
                'The selected entries were set to settled.',
                'Please use the back button in the toolbar to return to the start page.',
            ]
    except Exception as e:
        error = [e]

    return TemplateResponse(request, "message.html", {
        'page_title': f"Set Time Records To Settled",
        'success': success,
        'error': error,
    })


@login_required
@permission_required("doc.time_records_set_deleted")
def time_records_set_deleted(request, **kwargs):
    """
    Sets the selected time records to deleted.
    """

    if not request.POST:
        return HttpResponseRedirect(reverse("docs"))

    success = False
    error = False

    try:
        trs = TimeRecord.objects.filter(id__in=request.POST.getlist('tr') or [], user=request.user)
        for tr in trs:
            tr.deleted_at = timezone.now()
            tr.save()
            tr.doc.save()
            success = [
                'The selected entries have been deleted.',
                'Please use the back button in the toolbar to return to the start page.',
            ]
    except Exception as e:
        error = [e]

    return TemplateResponse(request, "message.html", {
        'page_title': f"Delete Time Records",
        'success': success,
        'error': error,
    })


@login_required
@permission_required("doc.time_analyse")
def time_analyse_download(request, **kwargs):
    """
    Returns a download in the specified format.
    """

    if not request.POST:
        return HttpResponseRedirect(reverse("docs"))

    rows = TimeRecord.objects.filter(id__in=request.POST.getlist('tr') or [], user=request.user, ) \
        .order_by('date', 'doc__title', 'description') \
        .values_list('date', 'doc__title', 'description', 'time', named=True)

    timestamp = timezone.now().strftime("%Y%m%d_%H%M%S")
    filename = f"timereport_{timestamp}"

    if request.POST.get('dcsv', default=False):
        output = io.StringIO()
        writer = csv.writer(output)
        writer.writerow(["Date", "Item", "Task", "Time [h]"])
        for row in rows:
            writer.writerow([row.date, row.doc__title, row.description, row.time])
        response = HttpResponse(output.getvalue(), content_type="text/csv")

doc/views/ajax.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.views.decorators.http import require_GET

from doc.models import Doc
from taggit.models import Tag


@require_GET
@login_required
def suggest_tags(request):
    """"""

    q = request.GET.get("q", "").lower()

    used_tags = Tag.objects.filter(taggit_taggeditem_items__content_type__model='doc') \
                           .values_list("name", flat=True).distinct()

    matching = sorted(
        tag for tag in used_tags if q in tag.lower()
    )[:10]

    return JsonResponse(matching, safe=False)

doc/views/checklist.py
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponseRedirect
from django.template.response import TemplateResponse
from django.urls import reverse

from doc.forms import ChecklistItemFormSet
from doc.models import Doc, ChecklistItem


@login_required
@permission_required("doc.edit")
def check_checklist(request, **kwargs):
    """"""

    doc_id = kwargs.get('id')

    try:
        entity = Doc.objects.get(pk=doc_id)
    except Doc.DoesNotExist as e:
        return TemplateResponse(request, "doc.html", {
            'page_title': f"Documentation - ID {doc_id}",
            'doc_id': doc_id,
            'error': 404,
        })

    if request.method == 'POST':
        for item in entity.checklist_items.all():
            key = f"check_{item.id}"
            item.checked = key in request.POST
            item.save()

    return HttpResponseRedirect(reverse("doc:detail", args=(entity.id,)))


@login_required
@permission_required("doc.edit")
def edit_checklist(request, **kwargs):
    """"""

    doc_id = kwargs.get('id')

    try:
        entity = Doc.objects.get(pk=doc_id)
    except Doc.DoesNotExist as e:
        return TemplateResponse(request, "doc.html", {
            'page_title': f"Documentation - ID {doc_id}",
            'doc_id': doc_id,
            'error': 404,
        })

    if request.method == 'POST':
        formset = ChecklistItemFormSet(request.POST)

        if formset.is_valid():
            existing_items = entity.checklist_items.all()
            form_items = formset.save(commit=False)
            submitted_ids = []

            for form in formset.forms:
                cleaned = form.cleaned_data
                item_id = cleaned.get('id')
                if isinstance(item_id, ChecklistItem):
                    item_id = item_id.id
                description = cleaned.get('description', '').strip()

                if item_id and not description:
                    ChecklistItem.objects.filter(id=item_id, doc=entity).delete()
                elif description:
                    item = form.save(commit=False)
                    item.doc = entity
                    item.save()
                    submitted_ids.append(item.id)

            for item in existing_items:
                if item.id not in submitted_ids and item.description.strip():
                    item.delete()

    return HttpResponseRedirect(reverse("doc:detail", args=(entity.id,)))

doc/views/md2pdf.py
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponseRedirect
from django.template.response import TemplateResponse
from django.urls import reverse

from doc.utils import doc_pdf, doc_pdfa


@login_required
@permission_required("doc.edit")
def create_pdf(request, **kwargs):
    """
    Creates a PDF based on the content of the specified document. The document
    will be saved in the File model but not set into relation with the document.
    After the rendering the client is redirected to the previously created PDF.
    """

    error = []
    doc_id = kwargs.get('id')

    if request.method != 'POST':
        return HttpResponseRedirect(reverse("doc:detail", args=(doc_id,)))

    try:
        variant = request.POST.get('variant', default=None)
        if variant == 'pdf':
            file = doc_pdf(doc_id)
        if variant == 'pdf-a':
            file = doc_pdfa(doc_id)
        if not file:
            error.append('The creation of the PDF of the content failed.')
    except Exception as e:
        error.append(f'An exception occurred: {e}')

    if error:
        return TemplateResponse(request, "message.html", {
            'page_title': f"PDF creation - ID {doc_id}",
            'doc_id': doc_id,
            'error': error,
        })

    return HttpResponseRedirect(file.file.url)

doc/templates/bulk_update.html
{% extends "base/base.html" %}
{% load static %}

{% block extra_css %}
<style>
    .btn-group .btn {
        min-width: 150px;
        text-align: left;
    }
</style>
{% endblock %}

{% block content %}
{% include 'bulk_update/navbar.html' %}
<div class="container">
    <h1 class="h2 mb-4">{{ page_title }}</h1>
    {% if no_docs_left %}
    <div class="alert alert-info d-flex align-items-center" role="alert">
        <i class="h1 bi bi-info-circle-fill me-4"></i>
        <div>
            <h2 class="h5 mb-1">No documents selected</h2>
            <div>
                You have selected either no documents or only revisions. After excluding
                revised documents, there are no remaining entries that could be updated.
                Please go back to the search and change or expand the selection.
            </div>
        </div>
    </div>
    {% else %}
    {% if show_initial_warning %}
    <div class="alert alert-warning d-flex align-items-center" role="alert">
        <i class="h1 bi bi-exclamation-triangle-fill me-4"></i>
        <div>
            <h2 class="h5 mb-1">No revisions / Immediate update</h2>
            <div>
                Please note that a bulk update - in contrast to individual processing -
                does not create any revisions of the affected documents.
                And the selected operation (adding/removing flags and tags) is performed
                immediately after clicking the corresponding button and is applied to all
                documents listed below.
            </div>
        </div>
    </div>
    {% endif %}
    {% if show_exclusion_deleted_info %}
    <div class="alert alert-info d-flex align-items-center" role="alert">
        <i class="h1 bi bi-info-circle-fill me-4"></i>
        <div>
            <h2 class="h5 mb-1">No bulk update on revisions</h2>
            <div>
                Revisions cannot be updated as part of a bulk update. The documents you
                selected with the status 'revision' have therefore been removed from the
                list of affected documents.
            </div>
        </div>
    </div>
    {% endif %}
    {% if error %}
    <div class="alert alert-danger d-flex align-items-center" role="alert">
        <i class="h1 bi bi-exclamation-octagon me-4"></i>
        <div>
            <h2 class="h5 mb-1">An exception occurred</h2>
            <ul>
                {% for e in error %}
                <li>{{ e }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
    {% endif %}
    {% if success %}
    <div class="alert alert-success d-flex align-items-center" role="alert">
        <i class="h1 bi bi-hand-thumbs-up me-4"></i>
        <div>
            <h2 class="h5 mb-1">Update successful</h2>
            <div>
                The update has been successfully completed.
            </div>
        </div>
    </div>
    {% endif %}
    {% if show_delete_warning %}
    <div class="alert alert-info d-flex align-items-center" role="alert">
        <i class="h1 bi bi-info-circle-fill me-4"></i>
        <div>
            <h2 class="h5 mb-1">Archived / deleted</h2>
            <div>
                A document can either be archived or deleted, but not both at the same time.
                If the 'Archive' action is executed, deleted documents are marked as not deleted
                again. Conversely, when the 'Delete' action is performed, the affected documents
                are automatically set to not archived.
            </div>
        </div>
    </div>
    {% endif %}
    <form class="mb-4 p-3 border rounded" method="post" action="{% url 'doc:bulk-update' %}">
        {% csrf_token %}
        {% for d in docs %}
        <input type="hidden" name="doc" value="{{ d.id }}">
        {% endfor %}
        <h2 class="h4 mb-3">Operations to be applied</h2>
        <div class="border rounded p-3 mb-3">
            <h3 class="h6 mb-3">Set / Unset Archive and Flag</h3>
            <div class="d-flex flex-row gap-4 mt-3">
                <div aria-label="Set / unset flag" class="btn-group" role="group">
                    <input autocomplete="off" class="btn-check" id="set-flag" name="set-flag" onchange="this.form.submit()" type="checkbox">
                    <label class="btn btn-success text-start pe-3" for="set-flag">
                        <i class="bi-flag-fill me-2"></i> Flag
                    </label>
                    <input autocomplete="off" class="btn-check" id="unset-flag" name="unset-flag" onchange="this.form.submit()" type="checkbox">
                    <label class="btn btn-outline-success" for="unset-flag">
                        <i class="bi-flag me-2"></i> Undo flag
                    </label>
                </div>
                <div aria-label="Set / unset archived" class="btn-group" role="group">
                    <input autocomplete="off" class="btn-check" id="set-archive" name="set-archived" onchange="this.form.submit()" type="checkbox">
                    <label class="btn btn-info text-start pe-3" for="set-archive">
                        <i class="bi-archive-fill me-2"></i> Archive
                    </label>
                    <input autocomplete="off" class="btn-check" id="unset-archived" name="unset-archived" onchange="this.form.submit()" type="checkbox">
                    <label class="btn btn-outline-info" for="unset-archived">
                        <i class="bi-archive me-2"></i> Undo archive
                    </label>
                </div>
                <div aria-label="Delete / undelete" class="btn-group" role="group">
                    <input autocomplete="off" class="btn-check" id="set-deleted" name="set-deleted" onchange="this.form.submit()" type="checkbox">
                    <label class="btn btn-danger text-start pe-3" for="set-deleted">
                        <i class="bi-trash-fill me-2"></i> Delete
                    </label>
                    <input autocomplete="off" class="btn-check" id="unset-deleted" name="unset-deleted" onchange="this.form.submit()" type="checkbox">
                    <label class="btn btn-outline-danger" for="unset-deleted">
                        <i class="bi-trash me-2"></i> Undo delete
                    </label>
                </div>
            </div>
        </div>
        <div class="border rounded p-3 mb-3">
            <h3 class="h6 mb-3">Add tags</h3>
            <div class="d-flex flex-row gap-3">
                <input aria-label="add-tag" class="form-control shadow-none border" id="add-tag" name="add-tag" placeholder="Tags, comma-separated">
                <button class="btn btn-secondary" type="submit">
                    <span class="bi-plus-circle-fill"/>
                </button>
            </div>
        </div>
        {% if tags %}
        <div class="border rounded p-3">
            <h3 class="h6 mb-3">Remove one of the following tags</h3>
            {% for tag in tags %}
            <button class="btn btn-outline-secondary btn-sm my-2 mt-0 me-1" type="submit" name="rm-tag" value="{{ tag.id }}">
                <span class="text-secondary-emphasis"><strong>{{ tag.slug|slice:":1"|upper }}</strong>{{ tag.slug|slice:"1:" }}</span>
            </button>
            {% endfor %}
        </div>
        {% endif %}
    </form>
    <h2 class="h4 mb-3">Documents affected by updates</h2>
    <div class="max-80-vh px-2 border rounded mb-4">
        <table class="table table-hover table-striped">
            <thead class="sticky-top">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">State</th>
                <th scope="col">Title</th>
                <th scope="col">Tags</th>
                <th scope="col">Created</th>
                <th scope="col">Updated</th>
            </tr>
            </thead>
            <tbody>
            {% for d in docs %}
            <tr class="selectable-row">
                <td>{{ d.id }}</td>
                <td class="text-nowrap">
                    {% if d.is_flagged %}
                    <i class="bi-flag-fill text-success me-2"></i>
                    {% else %}
                    <i class="bi-flag me-1 text-success opacity-50 me-2"></i>
                    {% endif %}
                    {% if d.is_archived %}
                    <i class="bi-archive-fill text-info me-2"></i>
                    {% else %}
                    <i class="bi-archive me-1 text-info opacity-50 me-2"></i>
                    {% endif %}
                    {% if d.deleted_at %}
                    <i class="bi-trash-fill text-danger"></i>
                    {% else %}
                    <i class="bi-trash me-1 text-danger opacity-50"></i>
                    {% endif %}
                </td>
                <td>{{ d.title }}</td>
                <td>{{ d.tag }}</td>
                <td class="text-nowrap">{{ d.created_at|date:"Y-m-d H:i" }}</td>
                <td class="text-nowrap">{{ d.updated_at|date:"Y-m-d H:i" }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {% endif %}
</div>
{% endblock content %}

{% block extra_js%}
<script>
  document.addEventListener("DOMContentLoaded", function () {
    const input = document.querySelector("#add-tag");

    if (input) {
      const tagify = new Tagify(input, {
        enforceWhitelist: false,
        whitelist: [],
        dropdown: {
          enabled: 1,
          maxItems: 10,
          position: "text",
          closeOnSelect: false
        },
        originalInputValueFormat: values => values.map(v => v.value).join(","),
      });

      tagify.on("input", async function(e) {
        let value = e.detail.value;
        let response = await fetch(`{% url 'doc:tag-suggest' %}?q=${encodeURIComponent(value)}`);
        let data = await response.json();
        tagify.settings.whitelist = data;
        tagify.dropdown.show.call(tagify, value);
      });
    } else {
      console.error("Tagify input not found");
    }
  });
</script>
{% endblock %}

doc/templates/cleanup.html
{% extends "base/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block extra_css %}{% endblock %}

{% block content %}
{% include 'status/navbar.html' %}
<div class="container">
    <h1 class="h2 mb-3">{{ page_title }}</h1>
    {% if form %}
    <div class="alert alert-warning" role="alert">
        The database should always be backed up before the clean-up. The data manipulations carried out
        as part of the clean-up are irreversible. If you have not yet made a dump, you should create
        one <a class="alert-link text-decoration-none" href="{% url 'doc:dump-database' %}">here</a>.
    </div>
    <div class="alert alert-info" role="alert">
        Cleaning up the database is of no practical benefit from the user's perspective. The search
        discriminates against entries marked as deleted and previous revisions. However, these can
        be included in the search if required. Cleansing therefore generally leads to a reduction
        in the utility value.
    </div>
    {% endif %}
    {% if faked %}
    <div class="alert alert-danger" role="alert">
        The data manipulations have not been executed. To actually change the data in the database,
        the commit must be explicitly confirmed.
    </div>
    {% endif %}
    {% if success %}
    <div class="alert alert-success" role="alert">
        {% for p in success %}
        <div class="my-2">
            {{ p }}
        </div>
        {% endfor %}
    </div>
    {% endif %}
    {% if error %}
    <div class="alert alert-danger" role="alert">
        {% for p in error %}
        <div class="my-2">
            {{ p }}
        </div>
        {% endfor %}
    </div>
    {% endif %}
    {% if form %}
    <form method="post" class="border rounded py-3 px-3">
        {% csrf_token %}
        {% crispy form %}
    </form>
    {% endif %}
</div>
{% endblock content %}

{% block extra_js %}{% endblock %}

doc/templates/tr_analyse_selection.html
{% extends "base/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block extra_css %}
<style>
    .selectable-row {
        cursor: pointer;
    }
    .selectable-row:hover {
        background-color: #f0f0f0; /* hellgrauer Hover-Effekt */
    }
</style>
{% endblock %}

{% block content %}
<div class="container">
    <div class="mb-3 p-2 border rounded d-flex justify-content-between bg-body-tertiary">
        <a class="btn btn-secondary me-2" data-toggle="tooltip" href="{% url 'doc:home' %}" role="button" title="Back">
            <i class="bi bi-chevron-double-left"></i>
        </a>
        <form>
            {% for doc in docs %}
            <input name="doc" type="hidden" value="{{ doc }}">
            {% endfor %}
            <div class="d-flex flex-row justify-content-end gap-2">
                <div class="d-flex gap-2 align-items-end">
                    <input class="form-control w-auto" id="dgte" max="{{ max_date|date:'Y-m-d' }}" min="{{ min_date|date:'Y-m-d' }}"
                           name="dgte" required type="date" value="{{ dgte|date:'Y-m-d' }}">
                    <input class="form-control w-auto" id="dlte" max="{{ max_date|date:'Y-m-d' }}" min="{{ min_date|date:'Y-m-d' }}"
                           name="dlte" required type="date" value="{{ dlte|date:'Y-m-d' }}">
                    <button class="btn btn-secondary" type="submit">
                        <i class="bi bi-funnel"></i>
                    </button>
                </div>
            </div>
        </form>
        <button class="btn btn-primary" form="selected-time-records" type="submit">
            <i class="bi bi-chevron-double-right"></i>
        </button>
    </div>
    <form id="selected-time-records" method="post" action="{% url 'doc:tr-analyse-preview' %}">{% csrf_token %}
        <div class="max-80-vh px-2 border rounded">
            <table class="table table-hover table-striped">
                <thead class="sticky-top">
                <tr>
                    <th scope="col"><input checked id="select-all" type="checkbox"/></th>
                    <th scope="col">Date</th>
                    <th scope="col">Item</th>
                    <th scope="col">Task</th>
                    <th class="text-end" scope="col">Hours</th>
                </tr>
                </thead>
                <tbody>
                {% for e in entities %}
                <tr class="selectable-row">
                    <th scope="row"><input checked class="row-checkbox" type="checkbox" name="tr" value="{{ e.id }}"/></th>
                    <td class="text-nowrap">{{ e.date|date:"Y-m-d" }}</td>
                    <td>{{ e.doc.title }}</td>
                    <td>{{ e.description }}</td>
                    <td class="text-end">{{ e.time|floatformat:2 }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </form>
</div>
{% endblock content %}

{% block extra_js%}
{% include 'tr_analyse_selection/extra_js.html' %}
{% endblock %}